spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: xxxidxxas 
            clientSecret: xxxsecretxxas 
          google:
            client-id: xxxidxxas 
            client-secret: xxxsecretxxas 